/turtlebot4_explorer:
  ros__parameters:
    map_path: "/home/mayerfel/ws/explore_ws/map"
    min_size: 10
    min_dist: 1.5
    map_given: true
    use_amcl: true
    do_exploration: false
    do_acquisition: true
    freespace_star_poses: true
    coverage_orientations: [0., 45., 90., 135., 180., 225., 270., 315.]
    coverage_pose_distance: 1.
